# Generated by Django 5.1 on 2024-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seating_capacity', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
    ]
