# Generated by Django 5.1 on 2024-10-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bularentals', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
