# Generated by Django 5.1 on 2024-10-21 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bularentals', '0003_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='feedback_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='No subject', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
