# Generated by Django 5.1 on 2024-10-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bularentals', '0004_contact_attachment_contact_feedback_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='feedback_type',
            field=models.CharField(choices=[('question', 'Question'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
