# Generated by Django 5.1 on 2024-10-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bularentals', '0005_alter_contact_attachment_alter_contact_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='feedback_type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
